#!/bin/bash

EXPECTED=$(cat test-files/output.json)
ACTUAL=$(./src/cogito "$(cat test-files/input.iam)")

if [ "$EXPECTED" = "$ACTUAL" ]; then
  echo 'Passed.'
else
  printf '=%.0s' {1..100}
  printf '\nExpected:\n'
  echo "$EXPECTED"
  printf '=%.0s' {1..100}
  printf '\nActual:\n'
  echo "$ACTUAL"
  printf '=%.0s' {1..100}
  printf '\nDiff:\n'
  diff <(echo "$EXPECTED") <(echo "$ACTUAL")
  exit 1
fi
