#!/usr/bin/env bash

CHECK_CFLAGS=' ' CHECK_LIBS=' ' ./configure
make
make dist

mkdir -p /root/rpmbuild/SOURCES/
FILENAME="$(ls cogito-*.tar.gz)"
mv "$FILENAME" "/root/rpmbuild/SOURCES/lib$FILENAME"

rpmbuild -ba amazon/libcogito.spec
mkdir -p pkg/
mv /root/rpmbuild/SRPMS/libcogito-*.rpm pkg/
